# ---------------------------------------------------------------------------------------------------------
# base configuration
nameOverride: "mediocre-db-postgresql"
fullnameOverride: "mediocre-db-postgresql"
namespace: "platform"
role: "database"

# ---------------------------------------------------------------------------------------------------------
# serviceaccount
serviceAccount:
  name: ""
  create: true
  automount: true

# ---------------------------------------------------------------------------------------------------------
# configmap - database
configMapPostgres:
   data:
    POSTGRES_PASSWORD: "T3st2025214" 

# ---------------------------------------------------------------------------------------------------------
# configmap - database
configMapDatabase:
  data:
    init.sql: |-
      CREATE SCHEMA grafana;
      CREATE SCHEMA keycloak;

# ---------------------------------------------------------------------------------------------------------
# role
Role:
  rules:
    - apiGroups: [""]
      resources: ["configmaps","secrets"]
      verbs: ["list","get"]

# ---------------------------------------------------------------------------------------------------------
# statefulset
StatefulSet:
  podManagementPolicy: "OrderedReady"
  nodeSelector:
    platform/role: database
  containers:
    postgresql:
      image: "487835535578.dkr.ecr.ap-southeast-1.amazonaws.com/system-devops-ecr-postgresql"
      tag: "latest"
      imagePullPolicy: "Always"
      resources:
        requests:
          memory: "500M"
          cpu: 0.25
        limits:
          memory: "2G"
          cpu: 1.0
      env:
        - name: POSTGRES_PASSWORD
          value: "T3st2025214"     
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: init-sql
          subPath: init.sql     
  volumes:
    - name: db-data
      hostPath:
        path: /opt/kube/postgresql
        type: Directory
    - name: init-sql
      configMap:
        name: postgresql-init-script
  securityContext:
    fsGroup: 1000
  imagePullSecrets:
    - name: mediocre-ecr-login
  tolerations:
    - key: platform/role
      operator: Equal
      value: "database"
      effect: NoExecute
  replicas: 1
  selector:
    matchLabels:
      platform/role: "database"

# ---------------------------------------------------------------------------------------------------------
# service - cluster
Service:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  clusterIP: None
  selector:
    app.kubernetes.io/name: "mediocre-db-postgresql"

# ---------------------------------------------------------------------------------------------------------
# service - nodeport
ServiceNode:
  type: NodePort
  ports:
    - targetPort: 5432
      port: 5432
      nodePort: 30432
  selector:
    app.kubernetes.io/name: "mediocre-db-postgresql"
