{{- if .Values.CloudIngress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mediocrewindapi.fullname" . }}
  labels:
    {{- include "mediocrewindapi.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}  
  annotations:
    {{- toYaml .Values.CloudIngress.annotations | nindent 4 }}
spec:
  ingressClassName: alb
  rules:
    {{- toYaml .Values.CloudIngress.rules | nindent 4 }}
{{- end }}