{{- if .Values.CloudIngress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mediocrewindapi.fullname" . }}
  namespace: {{ .Values.namespace }}   
  labels:
    {{- include "mediocrewindapi.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.CloudIngress.annotations | nindent 4 }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ include "mediocrewindapi.fullname" . }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mediocrewindapi.fullname" . }}
                port:
                  number: 8080
{{- end }}