---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mediocrewindapi.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mediocrewindapi.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.Role.rules | nindent 2 }}