---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mediocrewindapi.fullname" . }}
  namespace: {{ .Values.namespace }}  
  labels:
    {{- include "mediocrewindapi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mediocrewindapi.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mediocrewindapi.fullname" . }}
  apiGroup: rbac.authorization.k8s.io