---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediocrewindapi.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mediocrewindapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.Service.type }}
  ports:
    {{- toYaml .Values.Service.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.Service.selector | nindent 4 }}