apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
{{- with .Values.ConfigMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}