{{- if .Values.HorizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wordpress.fullname" . }}
  minReplicas: {{ .Values.HorizontalPodAutoscaler.spec.minReplicas }}
  maxReplicas: {{ .Values.HorizontalPodAutoscaler.spec.maxReplicas }}
  metrics:
    {{- if .Values.HorizontalPodAutoscaler.spec.metrics.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.HorizontalPodAutoscaler.spec.metrics.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.HorizontalPodAutoscaler.spec.metrics.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.HorizontalPodAutoscaler.spec.metrics.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}