---
{{- if .Values.Service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.Service.type }}
  ports:
    {{- toYaml .Values.Service.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.Service.selector | nindent 4 }}
{{- end }}

---
{{- if .Values.ServiceNode.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-node
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ServiceNode.type }}
  ports:
    {{- toYaml .Values.ServiceNode.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.ServiceNode.selector | nindent 4 }}
{{- end }}

---
{{- if .Values.ServiceALB.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ServiceALB.type }}
  ports:
    {{- toYaml .Values.ServiceALB.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.ServiceALB.selector | nindent 4 }}
{{- end }}