{{- if .Values.ServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.serviceAccountName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.ServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ServiceAccount.automount }}
{{- end }}