{{- if .Values.CloudIngress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wordpress.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: {{ include "wordpress.fullname" . }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    
spec:
  ingressClassName: {{ include "wordpress.fullname" . }}
  defaultBackend:
    service:
      name: {{ include "wordpress.fullname" . }}
      port:
        number: 80
{{- end }}