apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
rules:
  {{- toYaml .Values.Role.rules | nindent 2 }}