---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgresql.serviceAccountName" . }}
  namespace: {{ .Values.namespace }} 
  labels:
    {{- include  "postgresql.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}