---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
{{- with .Values.configMapPostgres.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}