---
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}  
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.Service.type }}
  ports:
    {{- toYaml .Values.Service.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.Service.selector | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "postgresql.fullname" . }}-node
  namespace: {{ .Values.namespace }}  
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ServiceNode.type }}
  ports:
    {{- toYaml .Values.ServiceNode.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.ServiceNode.selector | nindent 4 }}