---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "postgresql.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "postgresql.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
