---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-script
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
{{- with .Values.configMapDatabase.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}