---
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "mariadb.fullname" . }}-cluster
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  namespace:  {{ .Values.namespace }}    
spec:
  type: {{ .Values.ServiceCluster.type }}
  ports:
    {{- toYaml .Values.ServiceCluster.ports | nindent 4 }}
  clusterIP: {{ .Values.ServiceCluster.clusterIP  }}
  selector:
    {{- toYaml .Values.ServiceCluster.selector | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "mariadb.fullname" . }}-node
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  namespace:  {{ .Values.namespace }}    
spec:
  type: {{ .Values.ServiceNode.type }}
  ports:
    {{- toYaml .Values.ServiceNode.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.ServiceNode.selector | nindent 4 }}