---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}   
subjects:
  - kind: ServiceAccount
    name: {{ include "mariadb.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mariadb.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
