---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}    
spec:
  serviceName: {{ include "mariadb.fullname" . }}
  podManagementPolicy: {{ .Values.StatefulSet.podManagementPolicy }}
  template:
    metadata:
      name: {{ include "mariadb.fullname" . }}
      labels:
        {{- include "mariadb.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mariadb.fullname" . }}
      containers:
        - name: "mariadb"
          image: {{ .Values.StatefulSet.containers.mariadb.repository }}:{{ .Values.StatefulSet.containers.mariadb.tag }}
          imagePullPolicy: {{ .Values.StatefulSet.containers.mariadb.imagePullPolicy }}
          resources:
            requests:
              {{- toYaml .Values.StatefulSet.containers.mariadb.resources.requests | nindent 14 }}
            limits:
              {{- toYaml .Values.StatefulSet.containers.mariadb.resources.requests | nindent 14 }}
          envFrom:
            - configMapRef:
                name: {{ include "mariadb.fullname" . }}
          volumeMounts:
            {{- toYaml .Values.StatefulSet.containers.mariadb.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.StatefulSet.volumes | nindent 8  }}
      securityContext:
        {{- toYaml .Values.StatefulSet.securityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.StatefulSet.imagePullSecrets | nindent 8 }}
      tolerations:
        {{- toYaml .Values.StatefulSet.tolerations | nindent 8 }}
  replicas: {{ .Values.StatefulSet.replicas }}
  selector:
    {{- toYaml .Values.StatefulSet.selector | nindent 4 }}
    
