---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:aggregated-metrics-reader
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
{{- with .Values.ClusterRole.aggregatedMetricsReader.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:metrics-server
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
{{- with .Values.ClusterRole.metricsServer.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}