{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics-server.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
{{- end }}